# Generated by Django 5.2.3 on 2025-06-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='day',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='hour',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='persons',
            field=models.CharField(max_length=20),
        ),
    ]
