# Generated by Django 5.2.2 on 2025-06-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_tablebooking_day_alter_tablebooking_hour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('short_description', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('conclusion', models.TextField(blank=True)),
                ('author', models.CharField(choices=[('admin', 'Администратор'), ('chef', 'Шеф-повар')], max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='post_images/')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
