# Generated by Django 5.2.2 on 2025-06-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conclusion',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
